"""add languages, system_prompt, business_hours to agents

Revision ID: 202b22126fbb
Revises: 7f35ae95e3c0
Create Date: 2026-07-24 11:09:00.220742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '202b22126fbb'
down_revision: Union[str, Sequence[str], None] = '7f35ae95e3c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('languages', postgresql.ARRAY(sa.String()), server_default='{en}', nullable=False))
    op.add_column('agents', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'business_hours')
    op.drop_column('agents', 'system_prompt')
    op.drop_column('agents', 'languages')
    # ### end Alembic commands ###
