"""add conversation_turns table

Revision ID: 81a48e15bada
Revises: 5ecb59a516b6
Create Date: 2026-07-30 12:38:10.288004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a48e15bada'
down_revision: Union[str, Sequence[str], None] = '5ecb59a516b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_call_id'), 'conversation_turns', ['call_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_id'), 'conversation_turns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_turns_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_call_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    # ### end Alembic commands ###
