"""add call_summaries table

Revision ID: adf7f0110b64
Revises: fa345fc28737
Create Date: 2026-08-03 11:34:22.112515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf7f0110b64'
down_revision: Union[str, Sequence[str], None] = 'fa345fc28737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('final_intent', sa.String(), nullable=False),
    sa.Column('transfer_required', sa.Boolean(), nullable=False),
    sa.Column('transfer_department', sa.String(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_summaries_call_id'), 'call_summaries', ['call_id'], unique=True)
    op.create_index(op.f('ix_call_summaries_id'), 'call_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_summaries_id'), table_name='call_summaries')
    op.drop_index(op.f('ix_call_summaries_call_id'), table_name='call_summaries')
    op.drop_table('call_summaries')
    # ### end Alembic commands ###
